language: php

php:
  - 7.1

sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

install: travis_wait composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --verbose
